[delimiters.comment]
"#" = [".py", ".sh", ".yaml", ".yml", ".rb", ".pl", ".r"]
"//" = [".js", ".ts", ".c", ".cpp", ".java", ".cs", ".php", ".go", ".swift"]
"<!--" = [".html", ".xml", ".xhtml"]
"--" = [".sql", ".hs", ".lua"]
"%" = [".tex", ".m", ".matlab"]
"'" = [".vb", ".vbs"]
";" = [".asm"]
"REM" = [".bat"]

[delimiters]
keyword = "alphasort"
begin = "on"
end = "off"
